### ISSUE TITLE
how to manual install/update URF.Core.WebApi.Templates.1.0.0-rc.nupkg

### ISSUE THREAD

**Issue by neozhu** [urfnet/URF.Core.ApiControllers.Templates#1]
I modified some of the code according to my needs now want to re-install, how to do

**Comment by neozhu** [comment]
PM> Install-Package d:\URF.Core.WebApi.Templates.1.0.0-rc.nupkg
The 'Source' parameter is not respected for the transitive package management based project(s) Northwind.Api. The enabled sources in your NuGet configuration will be used. 
Restoring packages for D:\github\URF.Core.Sample\Northwind.Api\Northwind.Api.csproj...
Install-Package : Package 'URF.Core.WebApi.Templates 1.0.0-rc' has a package type 'Template' that is not supported by project 'Northwind.Api'.
At line:1 char:1
+ Install-Package d:\URF.Core.WebApi.Templates.1.0.0-rc.nupkg
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:08.4535118

**Comment by tonysneed** [comment]
These are different kinds of packages.  See here for instructions: https://github.com/TrackableEntities/AspNetCore.ApiControllers.Templates

**Comment by tonysneed** [comment]
I'll re-open this issue if you have any further questions.

**Comment by neozhu** [comment]
ok，Why can't  like asp.net  custom scaffolding extensions create a new controller?

**Comment by tonysneed** [comment]
These extensions have a different package name .. did you find it on NuGet and install per instructions in the link I gave?

**Comment by neozhu** [comment]
Thank you for reply immediately！ I did it.
 would you build like custom scaffolding wizard for .net core?  Is there such a sample?

**Comment by tonysneed** [comment]
Visual Studio has a built-in wizard for scaffolding controllers for an ASPNET Core project. Have you tried it?

**Comment by neozhu** [comment]
Is use Microsoft.VisualStudio.Web.CodeGeneration.Core? but I not found sample code project. I don't know how to do use

**Comment by tonysneed** [comment]
If you look st step 9 in the instructions, you’ll see how to use the VS wizard.

You can either use the command line CLI or the Visual Studio UI to scaffold controllers, and the razor templates located in your project will be used.

**Comment by neozhu** [comment]
thank you! I 
I got it and finally understood。

**Comment by tonysneed** [comment]
Great!  Ping me again if you need anything.
